spring.application.name = ex04

spring.datasource.url=jdbc:mysql://svc.sel3.cloudtype.app:32701/dgsw?useSSL=false&allowPubli
cKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver